# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/python/black
      rev: 24.3.0
      hooks:
          - id: black
            args: [--safe, --quiet, -l120]
            language_version: python3
    - repo: https://github.com/PyCQA/flake8
      rev: 7.0.0
      hooks:
          - id: flake8
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.15.1
      hooks:
          - id: pyupgrade
            args: [--py37-plus]
